---
# tasks/main.yml

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
- include: debian.yml
  when: ansible_os_family == 'Debian'
- include: suse.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'
- include: solaris.yml
  when: ansible_os_family == 'Solaris'

# Only run "update_cache=yes" if the last one is more than 3600 seconds ago
- name: package update (apt)
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes
  always_run: yes
  tags: apt