---
# tasks/redhat.yml
  
- name: set facts Redhat
  set_fact: 
    apache_service_name: httpd
    apache_user: apache
    apache_httpd_conf_path: /etc/httpd/conf/
    apache_httpd_conf: /etc/httpd/conf/httpd.conf
    iptables_conf_path: /etc/sysconfig/iptables
    mysql_service_name: mysqld
    mysql_user: mysql
  tags: 
    - common
    - yum

- name: selinux python bindings
  sudo: yes
  yum: name=libselinux-python state=present
  tags:
    - bootstrap
    - common
    - yum
    
- name: bootstrap epel-release install
  copy: src=ansible-bootstrap-epel.repo
    dest=/etc/yum.repos.d/
    owner=root group=root mode=0644
  sudo: yes
  tags:
    - bootstrap
    - common
    - yum
    - packages

- name: epel-release install
  yum: name=epel-release
    enablerepo=ansible-bootstrap-epel
    state=present
  sudo: yes
  tags:
    - bootstrap
    - common
    - yum
    - packages

- name: epel repository enable
  ini_file: dest=/etc/yum.repos.d/epel.repo
    section=epel
    option=enabled
    value=1
  sudo: yes
  tags:
    - bootstrap
    - common
    - yum
    - packages

- name: disable fastestmirror
  sudo: yes
  lineinfile: dest=/etc/yum/pluginconf.d/fastestmirror.conf regexp="^enabled=1" line="enabled=0" backrefs="yes"
  tags: yum
      
- name: Update all out of date packages (yum)
  yum: name=* state=latest
  sudo: yes
  always_run: yes
  tags: 
    - common
    - yum
    - upgrade

# CentOS 5 installing rsyslog doesn't uninstall sysklogd. So force it.
#
- name: Remove default conflicting packages (yum)
  sudo: yes
  yum: name={{item}} state=absent
  with_items:
    - sysklogd                      # we run rsyslog
  tags:
    - common
    - yum
  
- name: Ensure core packages are installed (yum)
  yum: name={{item}} state=present
  sudo: yes
  with_items:
      - bash
      - bind-utils  # bind9 host command
      - bzr
      - iptables
      - ntp
      - traceroute
      - rsyslog
      - openssh
      - vim-minimal
  tags: 
    - common
    - yum
    - packages

- name: Additional core packages are installed (CentOS 5)
  yum: name={{item}} state=present
  sudo: yes
  with_items:
      - virt-what
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 5 
  tags: 
    - common
    - yum
                
- name: Ensure core services are running
  service: name={{item}} state=running enabled=yes
  sudo: yes
  with_items:
      - ntpd
      - rsyslog
      - sshd
  tags: 
    - common
    - yum
    - packages
    - services

- name: Set iptables to autostart on boot
  sudo: yes
  command: /sbin/chkconfig iptables on 
  tags: iptables
  
- name: copy iptables rules
  sudo: yes
  copy: 
    src=iptables/up.rules
    dest={{iptables_conf_path}}
    owner=root
    group=root
    mode=0640
  tags: iptables

- name: iptables running
  sudo: yes
  service: name=iptables state=started
  sudo: yes
  tags: iptables
      
- name: restart iptables
  sudo: yes
  command: /etc/init.d/iptables restart
  tags: iptables
